apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-webhook.fullname" . }}
  labels:
    {{- include "go-webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-webhook.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - serve
            - --config
            - /app/configs/config.yaml
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.config.admin.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /admin/healthz
              port: admin
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /admin/healthz
              port: admin
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/configs
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "go-webhook.fullname" . }}
