// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/config": {
            "get": {
                "description": "Returns the runtime configuration as JSON. Sensitive fields (token, secret, password, key) are redacted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Runtime configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/healthz": {
            "get": {
                "description": "Returns ok if the service is running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/admin/rules": {
            "get": {
                "description": "Returns all currently loaded webhook forwarding rules with compile status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List loaded rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.RulesResponse"
                        }
                    }
                }
            }
        },
        "/webhook": {
            "post": {
                "description": "Receives a JSON payload, matches against loaded rules, transforms the body, and dispatches to target URLs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhook"
                ],
                "summary": "Receive and forward webhook",
                "parameters": [
                    {
                        "description": "Incoming webhook JSON payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.WebhookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.DispatchResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": ""
                },
                "rule_name": {
                    "type": "string",
                    "example": "alertmanager-to-lark"
                },
                "status_code": {
                    "type": "integer",
                    "example": 200
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "target_url": {
                    "type": "string",
                    "example": "https://open.larksuite.com/open-apis/bot/v2/hook/abc"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_BODY"
                },
                "error": {
                    "type": "string",
                    "example": "invalid JSON body"
                }
            }
        },
        "handler.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handler.RuleEntry": {
            "type": "object",
            "properties": {
                "compiled": {
                    "type": "boolean",
                    "example": true
                },
                "error": {
                    "type": "string"
                },
                "match": {
                    "type": "string",
                    "example": "len(payload.alerts) \u003e 0"
                },
                "method": {
                    "type": "string",
                    "example": "POST"
                },
                "name": {
                    "type": "string",
                    "example": "alertmanager-to-lark"
                },
                "target": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "handler.RulesResponse": {
            "type": "object",
            "properties": {
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.RuleEntry"
                    }
                }
            }
        },
        "handler.WebhookResponse": {
            "type": "object",
            "properties": {
                "dispatched": {
                    "type": "integer",
                    "example": 1
                },
                "matched": {
                    "type": "integer",
                    "example": 1
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.DispatchResult"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "go-webhook API",
	Description:      "Configurable webhook forwarding engine. Receives JSON webhooks, transforms payloads using expr rules, and forwards to target services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
